# Generated by Django 2.2 on 2020-03-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200305_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='profiles',
            field=models.ManyToManyField(to='event.Profile'),
        ),
    ]
