# Generated by Django 2.2 on 2020-03-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200305_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('name',)},
        ),
    ]
